# Generated by Django 3.1.7 on 2021-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAdjectiveAlsoSee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('also_see_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_also_see',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_action_id', models.IntegerField(blank=True, null=True)),
                ('anto_action_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_amount_id', models.IntegerField(blank=True, null=True)),
                ('anto_amount_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_amount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_colour_id', models.IntegerField(blank=True, null=True)),
                ('anto_colour_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_colour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_direction_id', models.IntegerField(blank=True, null=True)),
                ('anto_direction_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_gender_id', models.IntegerField(blank=True, null=True)),
                ('anto_gender_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoManner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_manner_id', models.IntegerField(blank=True, null=True)),
                ('anto_manner_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_manner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_personality_id', models.IntegerField(blank=True, null=True)),
                ('anto_personality_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_personality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_place_id', models.IntegerField(blank=True, null=True)),
                ('anto_place_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_quality_id', models.IntegerField(blank=True, null=True)),
                ('anto_quality_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_size_id', models.IntegerField(blank=True, null=True)),
                ('anto_size_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_state_id', models.IntegerField(blank=True, null=True)),
                ('anto_state_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveAntoTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_time_id', models.IntegerField(blank=True, null=True)),
                ('anto_time_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_anto_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveDerivedFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('derived_from_id', models.IntegerField(blank=True, null=True)),
                ('derived_from_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_derived_from',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_action_id', models.IntegerField(blank=True, null=True)),
                ('grad_action_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_color_id', models.IntegerField(blank=True, null=True)),
                ('grad_color_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_gender_id', models.IntegerField(blank=True, null=True)),
                ('grad_gender_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_light_id', models.IntegerField(blank=True, null=True)),
                ('grad_light_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_light',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradManner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_manner_id', models.IntegerField(blank=True, null=True)),
                ('grad_manner_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_manner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_quality_id', models.IntegerField(blank=True, null=True)),
                ('grad_quality_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_size_id', models.IntegerField(blank=True, null=True)),
                ('grad_size_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_state_id', models.IntegerField(blank=True, null=True)),
                ('grad_state_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_temperature_id', models.IntegerField(blank=True, null=True)),
                ('grad_temperature_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveGradTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_time_id', models.IntegerField(blank=True, null=True)),
                ('grad_time_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_grad_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveModifiesNoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('modifies_noun_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_modifies_noun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('link_type', models.CharField(max_length=100)),
                ('tbl_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_relations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveSenseNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('sense_num', models.IntegerField()),
                ('synset_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_adjective_sense_num',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdjectiveSimilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('similar_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_adjective_similar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAlsoSee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('also_see_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_also_see',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_action_id', models.IntegerField(blank=True, null=True)),
                ('anto_action_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_amount_id', models.IntegerField(blank=True, null=True)),
                ('anto_amount_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_amount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_colour_id', models.IntegerField(blank=True, null=True)),
                ('anto_colour_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_colour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_direction_id', models.IntegerField(blank=True, null=True)),
                ('anto_direction_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_gender_id', models.IntegerField(blank=True, null=True)),
                ('anto_gender_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoManner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_manner_id', models.IntegerField(blank=True, null=True)),
                ('anto_manner_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_manner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_personality_id', models.IntegerField(blank=True, null=True)),
                ('anto_personality_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_personality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_place_id', models.IntegerField(blank=True, null=True)),
                ('anto_place_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_quality_id', models.IntegerField(blank=True, null=True)),
                ('anto_quality_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_size_id', models.IntegerField(blank=True, null=True)),
                ('anto_size_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_state_id', models.IntegerField(blank=True, null=True)),
                ('anto_state_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbAntoTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_time_id', models.IntegerField(blank=True, null=True)),
                ('anto_time_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_anto_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbDerivedFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('derived_from_id', models.IntegerField(blank=True, null=True)),
                ('derived_from_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_derived_from',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_action_id', models.IntegerField(blank=True, null=True)),
                ('grad_action_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_color_id', models.IntegerField(blank=True, null=True)),
                ('grad_color_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_gender_id', models.IntegerField(blank=True, null=True)),
                ('grad_gender_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_light_id', models.IntegerField(blank=True, null=True)),
                ('grad_light_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_light',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradManner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_manner_id', models.IntegerField(blank=True, null=True)),
                ('grad_manner_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_manner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_quality_id', models.IntegerField(blank=True, null=True)),
                ('grad_quality_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_size_id', models.IntegerField(blank=True, null=True)),
                ('grad_size_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_state_id', models.IntegerField(blank=True, null=True)),
                ('grad_state_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_temperature_id', models.IntegerField(blank=True, null=True)),
                ('grad_temperature_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbGradTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_time_id', models.IntegerField(blank=True, null=True)),
                ('grad_time_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_grad_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbModifiesVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('modifies_verb_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_modifies_verb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('link_type', models.CharField(max_length=100)),
                ('tbl_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tbl_adverb_relations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAdverbSenseNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('sense_num', models.IntegerField()),
                ('synset_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_adverb_sense_num',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllSynset',
            fields=[
                ('synset_id', models.AutoField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_synset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('word', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=100)),
                ('sense_num', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_all_words',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblMorphRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending', models.CharField(max_length=20)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('pos', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_morph_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNearSynset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('near_synset_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_near_synset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAbilityVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('ability_verb_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_ability_verb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_action_id', models.IntegerField(blank=True, null=True)),
                ('anto_action_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_amount_id', models.IntegerField(blank=True, null=True)),
                ('anto_amount_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_amount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_colour_id', models.IntegerField(blank=True, null=True)),
                ('anto_colour_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_colour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_direction_id', models.IntegerField(blank=True, null=True)),
                ('anto_direction_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_gender_id', models.IntegerField(blank=True, null=True)),
                ('anto_gender_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoManner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_manner_id', models.IntegerField(blank=True, null=True)),
                ('anto_manner_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_manner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_personality_id', models.IntegerField(blank=True, null=True)),
                ('anto_personality_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_personality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_place_id', models.IntegerField(blank=True, null=True)),
                ('anto_place_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_quality_id', models.IntegerField(blank=True, null=True)),
                ('anto_quality_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_size_id', models.IntegerField(blank=True, null=True)),
                ('anto_size_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_state_id', models.IntegerField(blank=True, null=True)),
                ('anto_state_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAntoTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_time_id', models.IntegerField(blank=True, null=True)),
                ('anto_time_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_anto_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('attributes_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_attributes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounCapabilityVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('capability_verb_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_capability_verb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounCompound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('compound_id', models.IntegerField(blank=True, null=True)),
                ('compound_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_compound',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounDerivedFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('derived_from_id', models.IntegerField(blank=True, null=True)),
                ('derived_from_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_derived_from',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounFunctionVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('function_verb_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_function_verb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_action_id', models.IntegerField(blank=True, null=True)),
                ('grad_action_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_color_id', models.IntegerField(blank=True, null=True)),
                ('grad_color_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_gender_id', models.IntegerField(blank=True, null=True)),
                ('grad_gender_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_light_id', models.IntegerField(blank=True, null=True)),
                ('grad_light_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_light',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradManner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_manner_id', models.IntegerField(blank=True, null=True)),
                ('grad_manner_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_manner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_quality_id', models.IntegerField(blank=True, null=True)),
                ('grad_quality_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_size_id', models.IntegerField(blank=True, null=True)),
                ('grad_size_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_state_id', models.IntegerField(blank=True, null=True)),
                ('grad_state_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_temperature_id', models.IntegerField(blank=True, null=True)),
                ('grad_temperature_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounGradTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_time_id', models.IntegerField(blank=True, null=True)),
                ('grad_time_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_grad_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHoloComponentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('holo_component_object_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_holo_component_object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHoloFeatureActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('holo_feature_activity_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_holo_feature_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHoloMemberCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('holo_member_collection_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_holo_member_collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHoloPhaseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('holo_phase_state_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_holo_phase_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHoloPlaceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('holo_place_area_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_holo_place_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHoloPortionMass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('holo_portion_mass_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_holo_portion_mass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHoloPositionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('holo_position_area_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_holo_position_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHoloResourceProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('holo_resource_process_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_holo_resource_process',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHoloStuffObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('holo_stuff_object_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_holo_stuff_object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHypernymy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('hypernymy_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_hypernymy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounHyponymy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('hyponymy_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_hyponymy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounMeroComponentObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('mero_component_object_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_mero_component_object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounMeroFeatureActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('mero_feature_activity_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_mero_feature_activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounMeroMemberCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('mero_member_collection_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_mero_member_collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounMeroPhaseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('mero_phase_state_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_mero_phase_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounMeroPlaceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('mero_place_area_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_mero_place_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounMeroPortionMass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('mero_portion_mass_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_mero_portion_mass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounMeroPositionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('mero_position_area_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_mero_position_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounMeroResourceProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('mero_resource_process_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_mero_resource_process',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounMeroStuffObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('mero_stuff_object_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_mero_stuff_object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('link_type', models.CharField(max_length=100)),
                ('tbl_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tbl_noun_relations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblNounSenseNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('sense_num', models.IntegerField()),
                ('synset_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_noun_sense_num',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOntoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onto_id', models.IntegerField()),
                ('onto_data', models.CharField(blank=True, max_length=250, null=True)),
                ('onto_desc', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tbl_onto_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOntoMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('child_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_onto_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOntoNodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('onto_nodes_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_onto_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbl_name', models.CharField(max_length=100)),
                ('rel_type', models.CharField(max_length=100)),
                ('pos', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_relation_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSenseCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('sense_count', models.IntegerField(blank=True, null=True)),
                ('pos', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_sense_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAlsoSee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('also_see_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_also_see',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_action_id', models.IntegerField(blank=True, null=True)),
                ('anto_action_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_amount_id', models.IntegerField(blank=True, null=True)),
                ('anto_amount_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_amount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoColour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_colour_id', models.IntegerField(blank=True, null=True)),
                ('anto_colour_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_colour',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_direction_id', models.IntegerField(blank=True, null=True)),
                ('anto_direction_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_gender_id', models.IntegerField(blank=True, null=True)),
                ('anto_gender_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoManner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_manner_id', models.IntegerField(blank=True, null=True)),
                ('anto_manner_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_manner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_personality_id', models.IntegerField(blank=True, null=True)),
                ('anto_personality_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_personality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_place_id', models.IntegerField(blank=True, null=True)),
                ('anto_place_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_place',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_quality_id', models.IntegerField(blank=True, null=True)),
                ('anto_quality_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_size_id', models.IntegerField(blank=True, null=True)),
                ('anto_size_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_state_id', models.IntegerField(blank=True, null=True)),
                ('anto_state_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbAntoTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('anto_time_id', models.IntegerField(blank=True, null=True)),
                ('anto_time_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_anto_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbCausative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('causative_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_causative',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbCompounding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('compounding_id', models.IntegerField(blank=True, null=True)),
                ('compounding_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_compounding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbConjunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('conjunction_id', models.IntegerField(blank=True, null=True)),
                ('conjunction_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_conjunction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbDerivedFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('derived_from_id', models.IntegerField(blank=True, null=True)),
                ('derived_from_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_derived_from',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbEntailment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('entailment_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_entailment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_action_id', models.IntegerField(blank=True, null=True)),
                ('grad_action_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_action',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_color_id', models.IntegerField(blank=True, null=True)),
                ('grad_color_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradGender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_gender_id', models.IntegerField(blank=True, null=True)),
                ('grad_gender_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_gender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_light_id', models.IntegerField(blank=True, null=True)),
                ('grad_light_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_light',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradManner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_manner_id', models.IntegerField(blank=True, null=True)),
                ('grad_manner_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_manner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_quality_id', models.IntegerField(blank=True, null=True)),
                ('grad_quality_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_quality',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_size_id', models.IntegerField(blank=True, null=True)),
                ('grad_size_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_state_id', models.IntegerField(blank=True, null=True)),
                ('grad_state_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_temperature_id', models.IntegerField(blank=True, null=True)),
                ('grad_temperature_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbGradTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('synset_word', models.CharField(blank=True, max_length=100, null=True)),
                ('grad_time_id', models.IntegerField(blank=True, null=True)),
                ('grad_time_word', models.CharField(blank=True, max_length=100, null=True)),
                ('mid_synset_id', models.IntegerField(blank=True, null=True)),
                ('mid_word', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_grad_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbHypernymy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('hypernymy_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_hypernymy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('link_type', models.CharField(max_length=100)),
                ('tbl_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_relations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbSenseNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('sense_num', models.IntegerField()),
                ('synset_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_verb_sense_num',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblVerbTroponymy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('troponymy_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_verb_troponymy',
                'managed': False,
            },
        ),
    ]
