# Generated by Django 3.1.7 on 2021-03-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoWordNet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishHindiIdMapping',
            fields=[
                ('hindi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hindi_category', models.CharField(blank=True, max_length=100, null=True)),
                ('english_id', models.IntegerField(blank=True, null=True)),
                ('english_category', models.CharField(blank=True, max_length=100, null=True)),
                ('type_link', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'english_hindi_id_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('synset_words', models.CharField(blank=True, max_length=1000, null=True)),
                ('gloss', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'english_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnglishSynsetData1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('synset_words', models.CharField(blank=True, max_length=1000, null=True)),
                ('gloss', models.CharField(blank=True, max_length=1000, null=True)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'english_synset_data1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('hindi_id', models.CharField(max_length=11)),
                ('hindi_category', models.CharField(max_length=20)),
                ('english_id', models.CharField(max_length=11)),
                ('english_category', models.CharField(max_length=20)),
                ('comments', models.CharField(blank=True, max_length=4048, null=True)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'id_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IdMapping2',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('hindi_id', models.CharField(max_length=11)),
                ('hindi_category', models.CharField(max_length=20)),
                ('english_id', models.CharField(max_length=11)),
                ('english_category', models.CharField(max_length=20)),
                ('comments', models.CharField(blank=True, max_length=4048, null=True)),
                ('last_modified', models.DateTimeField()),
            ],
            options={
                'db_table': 'id_mapping2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllAssameseSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_assamese_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllBengaliSynsetData',
            fields=[
                ('synset_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=255, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_bengali_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllBodoSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_bodo_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllEnglishSynsetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.CharField(blank=True, max_length=1000, null=True)),
                ('gloss', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_all_english_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllGujaratiSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_gujarati_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllHindiSynsetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_hindi_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllHindiSynsetDataOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_hindi_synset_data_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllKannadaSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_kannada_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllKashmiriSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_kashmiri_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllKonkaniSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_konkani_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllMalayalamSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_malayalam_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllManipuriSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_manipuri_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllMarathiSynsetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synset_id', models.IntegerField()),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.CharField(blank=True, max_length=250, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_marathi_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllMeiteiSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_meitei_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllNepaliSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_nepali_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllOriyaSynsetData',
            fields=[
                ('synset_id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=255, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_oriya_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllPunjabiSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_punjabi_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllSanskritSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_sanskrit_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllSynsetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, db_column='Language', max_length=100, null=True)),
                ('synset_id', models.IntegerField()),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllTamilSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_tamil_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllTeluguSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_telugu_synset_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAllUrduSynsetData',
            fields=[
                ('synset_id', models.IntegerField(primary_key=True, serialize=False)),
                ('head', models.CharField(blank=True, max_length=100, null=True)),
                ('synset', models.TextField(blank=True, null=True)),
                ('gloss', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_all_urdu_synset_data',
                'managed': False,
            },
        ),
    ]
